### PR TITLE
Add a Makefile

### PR DESCRIPTION
**Pull request by Cat-Ion**
Invoking compilers is hard! Writing 'make\n' is easy! :D

### CODE REVIEW

**Comment by Cheeseness** [comment]
Thank you! :D

**Comment by Cheeseness** [comment]
I think this probably needs to be different for building on Mac and with mingw-gcc for Windows, but this will do for now \o/

**Comment by Cat-Ion** [comment]
Yeah, I've no idea what needs to be done for those platforms, so I just stuck to what I know =P

**Comment by Cheeseness** [comment]
I've been writing makefiles for Winter's Wake for Windows and Mac deployment, so I don't mind doing those ^_^

**Pull request merged**
